config/routes.rb
RocketHorse::Application.routes.draw do
  root :to => 'meetings#index'

  resources :meetings, :only => [:index,:show, :edit, :update, :create, :new, :destroy]
  resources :profiles, :only => [:index]
  resources :meetings_edits, :only => [:index]

  get  'meetings/:meeting_id/tips' => 'tips#index', :as => 'tips'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :id, :racecourse_id, :event, :date

  belongs_to :racecourse
  has_many :tips

  scope :sorted, order('date asc')

end

app/models/racecourse.rb
class Racecourse < ActiveRecord::Base
  attr_accessible :id, :name

  has_many :meetings

end

app/models/tip.rb
class Tip < ActiveRecord::Base
  attr_accessible :id, :meeting_id, :race_time, :horse_name, :odds, :information

  belongs_to :meeting

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #def current_user
  #  @user ||= User.find_by_id(cookies[:user_id]) if cookies[:user_id]
  #end
  #
  #def require_login
  #  redirect_to root_url unless current_user
  #end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def index
    @meetings = Meeting.sorted
  end

  def edit
    @meeting = Meeting.find(params[:id])
    @racecourses = Racecourse.all.collect {|a| [a.name, a.id]}
  end

  def update
    meeting = Meeting.find(params[:id])
    meeting.update_attributes(params[:meeting])

    respond_to do |format|
      format.html { redirect_to meetings_path }
      format.json { head :no_content }
    end
  end

  def new
    @meeting = Meeting.new(date:Date.today)
    @racecourses = Racecourse.all.collect {|a| [a.name, a.id]}
  end

  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to meetings_path, notice: 'Meeting successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_path }
      format.json { head :no_content }
    end
  end

end

app/controllers/meetings_edits_controller.rb
class MeetingsEditsController < ApplicationController

  def index
    @meetings = Meeting.sorted
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index

  end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController

  def index
    @meeting = Meeting.find(params['meeting_id'])
    @tips = @meeting.tips
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale = 1.0, user-scalable = no">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <!--<link rel="apple-touch-startup-image" href="/startup.png">-->
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div data-role="page">
  <%= yield %>
</div>

</body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
    <div class="field">
      <%= f.label :event %><br />
      <%= f.text_field :event %>
    </div>
    <div class="field">
      <%= f.label :date %><br />
      <%= f.text_field :date %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/meetings/edit.html.erb
<!DOCTYPE html>
<html>

<div class="ui-title" data-role="header" align="left" data-position="fixed">
  <a href="<%= meetings_edits_path %>" class="ui-btn-left" data-theme="a" data-rel="" data-icon="back">Back</a>
  <h1>Rocket Tips</h1>
</div>

<%= render 'form' %>

</div>
</html>

app/views/meetings/index.html.erb
<!DOCTYPE html>
<html>

<div class="ui-title" data-role="header" align="left" data-position="fixed">
  <a href="<%= profiles_path %>" class="ui-btn-left" data-theme="a" data-rel="" data-icon="gear">Profile</a>
  <a href="<%= meetings_edits_path %>" class="ui-btn-right" data-theme="a" data-rel="" data-icon="edit">Edit</a>
  <h1>Rocket Tips</h1>
</div>

<div data-role="content">
  <ul data-role="listview" id="fix-list">
    <% @meetings.each do |meeting| %>
        <li class="custom-list">
          <a href=<%= tips_path(meeting.id) %>>
            <div class="ui-grid-b">
              <div class="ui-block-a main-font" style="width:70%">
                <%= "#{DateTime.parse(meeting.date.to_s).strftime('%e %B')}: #{meeting.racecourse.name}" %>
                <br>
                <h10 class="kickoff">
                  <%= meeting.event %>
                </h10>
              </div>
              <div class="ui-block-b tips_count" style="width:30%">
                <% tips_count = meeting.tips.count %>
                <% unless tips_count == 0 %>
                <span class="label label-warning">
                  <%= tips_count > 1 ? "#{meeting.tips.count} tips" : "#{meeting.tips.count} tip" %>
                </span>
                <% end %>
              </div>
            </div>
          </a>
        </li>
    <% end %>
  </ul>
</div>
</html>

app/views/meetings/new.html.erb
<!DOCTYPE html>
<html>

<div class="ui-title" data-role="header" align="left" data-position="fixed">
  <a href="<%= meetings_edits_path %>" class="ui-btn-left" data-theme="a" data-rel="" data-icon="back">Back</a>
  <h1>Rocket Tips</h1>
</div>

    <%= form_for(@meeting) do |meeting| %>
    <fieldset>
      <div class="control-group custom-textbox">

        <%= meeting.label :racecourse %>
        <%= meeting.select :racecourse_id, @racecourses %>

        <br/>
        <%= meeting.label :event %>
        <%= meeting.text_field :event %>

        <br/>
        <%= meeting.label :date %>
        <%= meeting.text_field :date %>

        <br/>
        <%= meeting.submit 'Save', class: 'btn btn-large btn-primary' %>
      </div>
    </fieldset>
<% end %>

</div>
</html>

app/views/meetings_edits/index.html.erb
<!DOCTYPE html>
<html>

<div class="ui-title" data-role="header" align="left" data-position="fixed">
  <a href="<%= meetings_path %>" class="ui-btn-left" data-theme="a" data-rel="" data-icon="back">Back</a>
  <a href="<%= new_meeting_path %>" class="ui-btn-right" data-theme="a" data-rel="" data-icon="add">New</a>
  <h1>Rocket Tips</h1>
</div>

<div data-role="content">
  <ul data-role="listview" id="fix-list">
    <% @meetings.each do |meeting| %>
        <li class="custom-list">
          <div class="ui-grid-b">
            <div class="ui-block-a main-font" style="width:70%">
              <%= "#{DateTime.parse(meeting.date.to_s).strftime('%e %B')}: #{meeting.racecourse.name}" %>
              <br>
              <h10 class="kickoff">
                <%= meeting.event %>
              </h10>
            </div>
            <div class="ui-block-b main-font" style="width:30%">
              <td><%= link_to 'edit', edit_meeting_path(meeting) %></td>
              &nbsp
              <td><%= link_to 'delete', meeting, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </div>
          </div>
        </li>
    <% end %>
  </ul>
</div>
</html>

app/views/profiles/index.html.erb
<!DOCTYPE html>
<html>

<div class="ui-title" data-role="header" align="left" data-position="fixed">
  <a href="<%= meetings_path %>" class="ui-btn-left" data-theme="a" data-rel="" data-icon="back">Back</a>
  <h1>Profile</h1>
</div>


</html>

app/views/tips/index.html.erb
<!DOCTYPE html>
<html>

<div class="ui-title" data-role="header" align="left" data-position="fixed">
  <a href="<%= meetings_path %>" class="ui-btn-left" data-theme="a" data-rel="" data-icon="back">Back</a>

  <h1><%= "#{DateTime.parse(@meeting.date.to_s).strftime('%e %B')} #{@meeting.racecourse.name}" %></h1>
</div>

<div data-role="content">
  <ul data-role="listview" id="fix-list">
    <% @tips.each do |tip| %>
        <li class="custom-list">
          <div class="ui-grid-b">
            <div class="ui-block-a main-font" style="width:14%">
              <%= "#{DateTime.parse(tip.race_time.to_s).strftime('%H:%M')}" %>
            </div>
            <div class="ui-block-b main-font" style="width:86%">
            <%= "#{tip.horse_name} #{tip.odds}" %>
              <br>
              <h10 class="kickoff">
                <%= tip.information %>
              </h10>
            </div>
          </div>
        </li>
    <% end %>
  </ul>
</div>
</html>